### ISSUE TITLE
user-definable layouts?

### ISSUE THREAD

**Issue by TSSlade** [vertis/obsidian-image-layouts#1]
Does the plugin currently support user-defined layouts, or only those you've currently defined?

If no, will it at some point? Or is that deliberately out of scope?

Related but distinct: are the names of the layouts configurable?

**Comment by vertis** [comment]
I'm happy to accept PRs for alternative layouts, the initial version was simple enough to build but beyond this point it gets harder, to support a variety of layouts and allow adjusting them is complex. In the short term what layout(s) am I missing?

My thinking is that it's better to avoid the names altogether and do it visually with drag and drop, selecting files so that it becomes visual.
